version: '3'
services:
  jupyternb:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ./:/home/jovyan/work
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "my_db"
      MYSQL_USER: "akim"
      MYSQL_PASSWORD: "my_pass"
      MYSQL_ROOT_PASSWORD: "root_pass"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
